#!/usr/bin/env zsh

########## Git ##########
alias gitconfig="code --wait --reuse-window ~/.gitconfig"
alias gs="git status"
alias gad="git add ."
alias gc="git commit"
alias gcm="git commit -m"
alias gl="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"
alias gp="git push"
alias gd="git diff"
alias gb="git browse"
alias reset="git reset HEAD --hard; git clean -f -d"
alias clean="git branch --merged | grep -v '\*' | xargs -n 1 git branch -d"
alias branches="git branch -v"

########## NODE ##########
alias npme="PATH=$(npm bin):$PATH"
alias express="npx express-generator"
alias gfi="npx good-first-issue"
alias nuxt="npx create-nuxt-app"
alias probot="npx create-probot-app"
alias react="npx create-react-app"
alias gatsby="npx gatsby new"

########## Heroku ##########
alias h="heroku"
alias hl="h logs --tail -a"
alias ha="h addons -a"
alias hi="h apps:info -a"
alias hb="h run bash -a"
alias ho="h open -a"
alias hpg="h pg:info -a"
alias hc="h certs -a"
alias hca="h certs:auto -a"
alias hcad="h certs:auto:decr -a"
alias hsd="hs domains -a"
alias hbuildpacks="h buildpacks -a"
