#!/usr/bin/env zsh

set -e

# Bootstrap dotfiles
if [[ ! -d "$HOME/.dotfiles" ]]; then
  git clone https://github.com/nickcannariato/dotfiles .dotfiles
fi

# shellcheck source=lib/globals
source "$HOME/.dotfiles/lib/globals"

# shellcheck source=lib/functions
source "$DOTFILES_ROOT/lib/functions"

# Proper order to run setup scripts in
setups=(symlinks token homebrew dock code python ruby node rust postgres background-apps zsh)

for helper in "${setups[@]}"; do
  "$DOTFILES_ROOT/script/title" "Setting up $helper"
  "$DOTFILES_ROOT/script/helpers/$helper"
done

# create .hushlogin file in home directory
touch "$HOME/.hushlogin"

# update macOS plist files with my preferences
sudo plister "$HOME/.osx.yml"

# Remove strap.sh, which contains tokens
rm -f "$HOME/Downloads/strap.sh"

script/title "Fin."