#!/usr/bin/env bash
# Update all installed dependencies
# Usage: up

set -e

# shellcheck source=lib/globals
source "/$HOME/.dotfiles/lib/globals"

# shellcheck source=lib/functions
source "/$DOTFILES_ROOT/lib/functions"

pushd $DOTFILES_ROOT

script/title "Updating Homebrew..."
brew update
brew upgrade

script/title "Updating App Store apps"
mas upgrade

script/title "Updating to the latest Node LTS "
script/helpers/node

script/title "Updating Python(s)"
pyenv global system
script/helpers/python

script/title "Updating Ruby"
script/helpers/ruby

script/title "Updating Rust"
script/helpers/rust

script/title "Updating Oh My ZSH"
/bin/sh "$ZSH/tools/upgrade.sh"


popd