#! /usr/bin/env bash

##############################
#
# General, globally available functions. Language specific functions or environment variables
# found in the file named for that language in this folder
#
##############################

# Make a directory and immediately switch to it (will create the full path if it doesn't exist)
function mkcd {
    mkdir -p "$1" && cd "$1" || exit 1
}

# Automatically interpret the file extension and extract it with the appropriate incantation
function extract () {
    if [ -f "$1" ]; then
        case $1 in
            *.tar.bz2) tar xvjf '$1' ;;
            *.tar.gz) tar xvzf '$1' ;;
            *.tar.xz) tar xvJf '$1' ;;
            *.bz2) bunzip2 '$1' ;;
            *.rar) unrar x '$1' ;;
            *.gz) gunzip '$1' ;;
            *.tar) tar xvf '$1' ;;
            *.tbz2) tar xvjf '$1' ;;
            *.tgz) tar xvzf '$1' ;;
            *.zip) unzip '$1' ;;
            *.Z) uncompress '$1' ;;
            *.7z) 7z x '$1' ;;
            *) echo "'$1' cannot be extracted via extract()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

# Quickly navigate up the directory structure an arbitrary number of folders
up() {
    if [ "$#" -eq 0 ]; then
        cd .. || exit 1
    else
        local i=""

        for ((j=0; j<$1; j++)); do
            i=${i}../
        done

        cd $i || exit 1
    fi
}

# Backup a file with a timestamp
backup () {
    cp "$1" "$1_$(date +%Y%m%d_%H%M%S)"
}

# Watch a file and print it's contents to the terminal every 1 second
watchfile () {
    watch -n 1 cat "$1"
}

# Edit a file using whatever EDITOR is configured globally
edit () {
  "$EDITOR $1"
}
