#!/usr/bin/env bash

# Remove all apps from the dock
dockutil --list | awk -F"\t" '{print $1}' | while read -r line; do
    dockutil --remove "$line"
done

# Give dock time to restart
sleep 2

if [[ $(whoami) == "ncannariato" ]]; then
    apps=("Google Chrome" "Visual Studio Code" "Slack" "Spotify" "Signal" "Dash" "Postico")
else
    apps=("Google Chrome" "Visual Studio Code" "Slack" "Spotify" "Signal" "Dash" "zoom.us" "Postico")
fi

# Re-add the apps we want
for app in "${apps[@]}"; do
    echo "adding $app to dock"
    dockutil --add "/Applications/$app.app"
    sleep 2
done

dockutil --add "$HOME/Downloads" --display folder --view list
dockutil --add "$HOME/Code" --display folder --view list