#!/usr/bin/env bash
# Set up Homebrew

if ! brew bundle check --global --verbose; then
    brew bundle install --global --force --verbose
fi

# Delete zoom if I'm on my work computer
if [[ $(whoami) == "ncannariato" ]]; then
    brew cask uninstall zoomus
fi