#! /usr/bin/env bash

luarocks install mjolnir.alert
luarocks install mjolnir.application
luarocks install mjolnir.fnutils
luarocks install mjolnir.bg.grid
luarocks install mjolnir.hotkey
luarocks install mjolnir.screen
luarocks install mjolnir.geometry
luarocks install mjolnir.keycodes

