#!/usr/bin/env zsh
# Set up pyenv, pip, and system packages

# shellcheck source=lib/globals
source "$HOME/.files/lib/globals"
# shellcheck source=lib/functions
source "$DOTFILES_ROOT/lib/functions"

# Prevent Conda's base environment from activating by default
conda config --set auto_activate_base false

script/helpers/pyenv
gpip install --upgrade --force-reinstall -r "$DOTFILES_ROOT/data/python-global.txt"
