#!/usr/bin/env bash
# Set up pyenv, poetry, pip, and system packages

# shellcheck source=lib/globals
source "$HOME/.dotfiles/lib/globals"
# shellcheck source=lib/functions
source "$DOTFILES_ROOT/lib/functions"

# Prevent Conda's base environment from activating by default
conda config --set auto_activate_base false

script/helpers/pyenv
script/helpers/poetry
gpip install --upgrade --force-reinstall -r "$DOTFILES_ROOT/data/python-global.txt"
