#!/usr/bin/env zsh
# Setups up symlinks from .dotfiles to home directory

# shellcheck source=lib/globals
source "/$HOME/.dotfiles/lib/globals"

# shellcheck source=lib/functions
source "/$DOTFILES_ROOT/lib/functions"

link_safe .gitconfig
link_safe .gitignore-global
link_safe .Brewfile
link_safe .mongorc.js
link_safe .osx.yml

mkdir_safe ".mjolnir/"
link_safe .mjolnir/init.lua

mkdir_safe "Library/LaunchAgents/"
link_safe Library/LaunchAgents/com.cannariato.nick.tmpreaper.plist
link_safe Library/LaunchAgents/com.cannariato.nick.update.plist

mkdir_safe "Library/Spelling/"
link_safe Library/Spelling/LocalDictionary

mkdir_safe "Library/Application Support/Code/User/"
link_safe Library/Application\ Support/Code/User/settings.json
link_safe Library/Application\ Support/Code/User/keybindings.json

python=(conda click django flask fastapi learning oscontrib packages scripts)
for folder in "${python[@]}"; do
  mkdir_safe "Code/python/${folder}"
done

node=(vue react express oclif scripts learning oscontrib)
for folder in "${node[@]}"; do
  mkdir_safe "Code/node/${folder}"
done

rust=(scripts learning oscontrib)
for folder in "${rust[@]}"; do
  mkdir_safe "Code/rust/${folder}"
done

ruby=(rails sinatra jekyll scripts learning oscontrib)
for folder in "${ruby[@]}"; do
  mkdir_safe "Code/ruby/${folder}"
done

mkdir_safe ".ssh/"
link_safe .ssh/config

echo "Symlinks set."