#!/usr/bin/env python3

import os
from pathlib import Path
import subprocess as sub
import sys
from typing import List


def get_packages() -> List[str]:
    """
    Returns a list of npm packages to install globally using `npm i -g`
    """
    if os.getenv("DOTFILES_ROOT"):
        DOTFILES_ROOT = Path(os.getenv("DOTFILES_ROOT"))

    if not DOTFILES_ROOT.exists():
        print(f"the DOTFILES_ROOT path ({DOTFILES_ROOT}) appears to be missing!")
        sys.exit(1)

    with open(DOTFILES_ROOT / "data" / "npm-global.txt") as f:
        packages = f.read().splitlines()

    return packages


def npm_global_install(package: str):
    """
    Attempt to install a specific node package globally

    :param package: The name of an npm installable package
    """
    try:
        subprocess.run(["npm", "install", "-g", package], check=True, encoding='utf-8')
    except sub.CalledProcessError:
        print(f"Problem encountered when installing {package}!\n",
              "Review the output above or manually debug the issue later")
        sys.exit(1)


if __name__ == "__main__":
    packages = get_packages()

    for package in packages:
        npm_global_install(package)
