#!/usr/bin/env zsh
# Setup up pyenv

# shellcheck source=lib/globals
source "$HOME/.files/lib/globals"
source "$DOTFILES_ROOT/lib/functions"

command -v pyenv >/dev/null 2>&1 || { echo >&2 brew install pyenv; eval "$(pyenv init -)"; }

echo "Latest Python version is $(latest_py3)"

if [ "$(pyenv global)" = "system" ]; then
  pyenv install "$(latest_py3)"
  pyenv install "$(latest_py2)"
  pyenv global "$(latest_py2)" "$(latest_py2)"
  pyenv rehash
fi

