#!/usr/bin/env zsh
# Setups up symlinks from .files to home directory

# shellcheck source=lib/globals
source "/$HOME/.files/lib/globals"

# shellcheck source=lib/functions
source "/$DOTFILES_ROOT/lib/functions"

link_safe .gitconfig
link_safe .gitignore-global
link_safe .Brewfile
link_safe .mongorc.js
link_safe .mackup.cfg

mkdir_safe ".mjolnir"
link_safe .mjolnir/init.lua

mkdir_safe "Library/LaunchAgents/"
link_safe Library/LaunchAgents/com.cannariato.nick.tmpreaper.plist
link_safe Library/LaunchAgents/com.cannariato.nick.update.plist

mkdir_safe "Library/Spelling/"
link_safe Library/Spelling/LocalDictionary

mkdir_safe Code/python/django
mkdir_safe Code/python/flask
mkdir_safe Code/python/fastapi
mkdir_safe Code/python/click
mkdir_safe Code/python/oscontrib
mkdir_safe Code/rust/oscontrib
mkdir_safe Code/node/oscontrib

mkdir_safe .ssh
link_safe .ssh/config

echo "Symlinks set."